set nocompatible " fuck off vi

execute pathogen#infect()
filetype plugin indent on

colorscheme badwolf
filetype on
syntax on

set number                  "show line number
set cursorline

"shows trailing spaces as dots
set list
set listchars=trail:·

set tabstop=4               "tab stuff
set shiftwidth=4
set expandtab
set softtabstop=4

"make files need tabs
autocmd FileType make setlocal noexpandtab

set autoindent
set smartindent

set hlsearch                "highlight search items
set incsearch               "show maches as you search

set noswapfile

"C L-R changes tab
"A L-R moves current tab
nnoremap <C-H> :tabprevious<CR>
nnoremap <C-L> :tabnext<CR>


"Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


