set nocompatible

colorscheme badwolf
syntax enable

set number                  "show line number
set cursorline

"shows trailing spaces as dots
set list
set listchars=trail:·

set tabstop=4               "tab stuff
set shiftwidth=4
set autoindent
set smartindent

set hlsearch                "highlight search items
set incsearch               "show maches as you search

set noswapfile

"C L-R changes tab
"A L-R moves current tab
nnoremap <C-H> :tabprevious<CR>
nnoremap <C-L> :tabnext<CR>
