
# ~/.bashrc
#

export VISUAL='vim'

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias fuck='sudo $(history -p !!)'
alias py='/usr/bin/env python3'
alias rm='rm -r'

#PS1='\u@\h \w>'
#PS1='[\u@\h \W]\$ '
PS1="\[\033[1;36m\]\u:\w\[\033[1;33m\]-> \[\033[0m\]"
