#
# ~/.bashrc
#

#Allows 256 color support on my xfce4-arch machine
#Needed for vim basically
if [ "$COLORTERM" == "xfce4-terminal" ]; then
    export TERM=xterm-256color
fi

export VISUAL='vim'

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias fuck='sudo $(history -p !!)'
#alias vim=nvim
#alias sudo='sudo '

#PS1='[\u@\h \W]\$ '
PS1="\[\033[1;36m\]\u\[\033[1;33m\]-> \[\033[0m\]"
